// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for macos - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvzQDGbU8ndDGJ3mGCeWA0mSsCNRhsbt0',
    appId: '1:506976961145:web:551d2afd7dc9f0e8240aa8',
    messagingSenderId: '506976961145',
    projectId: 'woofcare-a9fac',
    authDomain: 'woofcare-a9fac.firebaseapp.com',
    storageBucket: 'woofcare-a9fac.firebasestorage.app',
    measurementId: 'G-FJDV4K81CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHdWdQorxOsL7c_jmxHelaKXCveKnH4d0',
    appId: '1:506976961145:android:b19e9a2b082f7b95240aa8',
    messagingSenderId: '506976961145',
    projectId: 'woofcare-a9fac',
    storageBucket: 'woofcare-a9fac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwsHu9KMZFTj3-0tHW79d2fzmNgDRbBR0',
    appId: '1:506976961145:ios:9c902046c4a17cb8240aa8',
    messagingSenderId: '506976961145',
    projectId: 'woofcare-a9fac',
    storageBucket: 'woofcare-a9fac.firebasestorage.app',
    iosBundleId: 'com.epics.woofcare',
  );
}
